import XCTest

final class ClipboardPolicyTests: XCTestCase {
    func testImportedWritesKeepTheLocalTokenAndNewCopiesInvalidateIt() {
        var versions = ClipboardRevision()
        XCTAssertFalse(versions.canApply(expectedLocal: 0, current: 0))
        versions.capture(10)
        XCTAssertTrue(versions.canApply(expectedLocal: 10, current: 10))
        versions.imported(11)
        XCTAssertTrue(versions.canApply(expectedLocal: 10, current: 11))
        versions.imported(12)
        XCTAssertTrue(versions.canApply(expectedLocal: 10, current: 12))
        XCTAssertFalse(versions.canApply(expectedLocal: 10, current: 13))
        versions.capture(13)
        XCTAssertFalse(versions.canApply(expectedLocal: 10, current: 13))
        XCTAssertTrue(versions.canApply(expectedLocal: 13, current: 13))
    }

    func testPrivateGeneratedAndFileClipboardMarkersAreExcluded() {
        for marker in [
            "org.nspasteboard.ConcealedType",
            "org.nspasteboard.TransientType",
            "org.nspasteboard.AutoGeneratedType",
            "com.agilebits.onepassword",
            "public.file-url",
            ClipboardPasteboard.ownType.rawValue
        ] {
            XCTAssertTrue(ClipboardPasteboard.excludedTypes.contains(marker))
        }
        XCTAssertFalse(ClipboardPasteboard.excludedTypes.contains("public.utf8-plain-text"))
    }
}
