import AppKit

/// All potentially blocking pasteboard reads stay off the input/main run loops.
final class ClipboardPasteboard: @unchecked Sendable {
    struct Snapshot: Sendable {
        let epoch: UInt32
        let generation: UInt64
        let revision: Int
        let text: Data?
        let announce: Bool
    }

    static let ownType = NSPasteboard.PasteboardType("io.github.amadeus.deuskvm.clipboard")
    static let excludedTypes: Set<String> = [
        "org.nspasteboard.TransientType", "org.nspasteboard.ConcealedType", "org.nspasteboard.AutoGeneratedType",
        "de.petermaurer.TransientPasteboardType", "com.typeit4me.clipping", "Pasteboard generator type",
        "com.agilebits.onepassword", "public.file-url", ownType.rawValue
    ]
    private let gate = NSLock()
    private var permittedGeneration: UInt64 = 0
    private var generation: UInt64 = 0
    private var permitted = false
    private let queue = DispatchQueue(label: "DeusKVM.clipboard")
    private var timer: DispatchSourceTimer?
    private var epoch: UInt32 = 0
    private var enabled = false
    private var versions = ClipboardRevision()
    private var priming = true
    private var pendingYield = false
    private struct Pending {
        let text: Data
        let revision: Int
        let deadline: TimeInterval
    }

    private var pending: Pending?
    private let snapshot: @Sendable (Snapshot) -> Void
    private let yielded: @Sendable (UInt32, UInt64) -> Void

    init(snapshot: @escaping @Sendable (Snapshot) -> Void, yielded: @escaping @Sendable (UInt32, UInt64) -> Void) {
        self.snapshot = snapshot; self.yielded = yielded
    }

    @discardableResult
    func configure(epoch: UInt32, enabled: Bool) -> UInt64 {
        let next = gate.withLock {
            permittedGeneration &+= 1; permitted = enabled
            return permittedGeneration
        }
        queue.async { [self] in
            generation = next
            self.epoch = epoch; self.enabled = enabled
            versions = ClipboardRevision(); pending = nil; priming = true; pendingYield = false
            if !enabled { timer?.cancel(); timer = nil; return }
            if timer == nil {
                let source = DispatchSource.makeTimerSource(queue: queue)
                source.schedule(deadline: .now(), repeating: .milliseconds(200))
                source.setEventHandler { [weak self] in self?.poll() }
                source.resume(); timer = source
            }
        }
        return next
    }

    func yield() {
        queue.async { [self] in pendingYield = true; poll() }
    }

    func write(_ text: Data, epoch: UInt32, revision: Int) {
        queue.async { [self] in
            guard enabled, self.epoch == epoch else { return }
            pending = Pending(text: text, revision: revision, deadline: ProcessInfo.processInfo.systemUptime + 2)
            poll()
        }
    }

    private var canAccess: Bool {
        gate.withLock { permitted && permittedGeneration == generation }
    }

    private func poll() {
        guard enabled, canAccess else { return }
        let board = NSPasteboard.general
        let revision = board.changeCount
        if versions.observed != revision {
            pending = nil
            let types = Set((board.types ?? []).map(\.rawValue))
            var bytes: Data?
            if types.isDisjoint(with: Self.excludedTypes),
               let data = board.data(forType: .string), data.count <= ClipboardTransfer.maximumBytes * 2
            {
                bytes = ClipboardTransfer.text(String(data: data, encoding: .utf8))
            }
            guard canAccess, board.changeCount == revision else { return }
            versions.capture(revision)
            snapshot(Snapshot(epoch: epoch, generation: generation, revision: revision, text: bytes, announce: !priming))
            priming = false
        }
        if pendingYield { pendingYield = false; yielded(epoch, generation) }
        guard let update = pending else { return }
        guard versions.canApply(expectedLocal: update.revision, current: revision), ProcessInfo.processInfo.systemUptime <= update.deadline,
              let text = ClipboardTransfer.decode(update.text) else { pending = nil; return }
        let item = NSPasteboardItem()
        item.setString(text, forType: .string)
        item.setData(Data(), forType: Self.ownType)
        item.setData(Data(), forType: NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"))
        guard canAccess, board.changeCount == revision else { pending = nil; return }
        board.clearContents()
        if board.writeObjects([item]) { versions.imported(board.changeCount); pending = nil }
    }

    deinit { timer?.cancel() }
}
