name: Build

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:
    inputs:
      version:
        description: "v*.*.*"
        required: true
        type: string

jobs:
  build:
    strategy:
      matrix:
        platform: [mac]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v7

      - name: Bootstrap
        env:
          CI_PRIMARY_REPOSITORY_PATH: ${{ github.workspace }}
        run: |
          sudo xcode-select -s /Applications/Xcode_26.3.app
          ci_scripts/ci_post_clone.sh

      - name: Build
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_GIT_URL: ${{ secrets.MATCH_GIT_URL }}
        run: fastlane ${{ matrix.platform }} release

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform }}
          path: |
            build/*.pkg
          if-no-files-found: ignore

  publish:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v8
        with:
          path: artifacts

      - name: Publish (GitHub)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          TAG: ${{ github.event.inputs.version || github.ref_name }}
        run: |
          gh release create "$TAG" \
            artifacts/mac/*.pkg \
            --title "$TAG"
